apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: hulk
  namespace: 1
  labels:
    app: hulk
spec:
  version: 8.7.0
  count: 1
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest
  elasticsearchRef:
    name: hulk