apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationSetDemo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: https://github.com/jethropick/elasticsearch.git
      revision: HEAD
      directories:
      - path: Environments/RepeatableEnvironment/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: elasticsearch
      source:
        repoURL: https://github.com/jethropick/elasticsearch.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        server: https://argocddemo-dns-eqy5clje.hcp.northeurope.azmk8s.io:443
        namespace: '{{ path.basename }}'
      syncpolicy:  
        automated:    
          prune: true    
          selfHeal: true