---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-read
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    # Select coordinating nodes
    elasticsearch.k8s.elastic.co/cluster-name: "cluster-1"
    elasticsearch.k8s.elastic.co/node-master: "false"
    elasticsearch.k8s.elastic.co/node-data: "false"
    elasticsearch.k8s.elastic.co/node-ingest: "false"
    elasticsearch.k8s.elastic.co/node-ml: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-write
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    # Select ingest nodes
    elasticsearch.k8s.elastic.co/cluster-name: "cluster-1"
    elasticsearch.k8s.elastic.co/node-ingest: "true"