apiVersion: v1
kind: Service
metadata:
  name: "elasticsearch-write"
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    # Select ingest nodes
    elasticsearch.k8s.elastic.co/cluster-name: "cluster"
    elasticsearch.k8s.elastic.co/node-ingest: "true"