apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-read
spec:
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: "ne-2"

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-write
spec:
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: "ne-2"